# aml.properties dung cho DEMO CALLJ (tro toi Mock AML server tren localhost)
# File nay duoc dat TRUOC trong classpath nen ConfigLoader se doc file nay thay cho src/main/resources/aml.properties
based.url=http://localhost:8089
getToken.url=/AMLWS/api/GetToken
getTokenExposure.url=/AMLWS_EXPOSURE/api/GetToken
realTimeScan.url=/AMLWS/api/RealtimeScan
realTimeExposure.url=/AMLWS_EXPOSURE/api/RealTimeExposure
realTimeApprovalStatus.url=/AMLWS/api/RealTimeApproval
auth.id=t24
auth.pw=demo@123
sqlite.db.path=%TAFJ_HOME%/data/AMLScan.db
